version: '3.7'
services:

  # If local ROMs cache is required, then uncomment rsync service
  #rsync:
  #  build: 
  #    context: ./rsync
  #  image: alpine-rsync:local
  #  container_name: Arcade_rsync
  #  volumes:
  #    - roms:/mnt/remote:ro
  #    - ./rsync/roms:/mnt/local
  #  # Run rsync once per day
  #  command: >
  #    sh -c "rsync -avh /mnt/remote/ /mnt/local/ &&
  #           sleep 86400"
  #  restart: always

  samba:
    # https://github.com/dperson/samba
    image: dperson/samba
    container_name: Arcade_smb-proxy
    volumes:
      # If local ROMs cache is required, then toggle comments on the below volumes
      - roms:/mnt:ro
      #- ./rsync/roms:/mnt:ro
    networks:
      arcade_vlan:
        ipv4_address: 172.16.64.2
    restart: always
    ports:
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    stdin_open: true
    tty: true
    #-s "<name;/path>[;browse;readonly;guest;users;admins;writelist;comment]"
    #-u "<username;password>[;ID;group;GID]"
    #-p Set ownership and permissions on the shares
    command: '-s "roms;/mnt;yes;yes;yes"'

  mediawiki:
    image: mediawiki
    container_name: Arcade_wiki
    restart: always
    networks:
      arcade_vlan:
        ipv4_address: 172.16.64.3
    ports:
      - 8080:80
    volumes:
      - /var/www/html/images
      # After initial setup, download LocalSettings.php to the same directory as
      # this yaml and uncomment the following line and use compose to restart
      # the mediawiki service
      - ./mediawiki/LocalSettings.php:/var/www/html/LocalSettings.php:ro
      - ./mediawiki/logo.png:/var/www/html/resources/assets/wiki.png:ro
      - ./mediawiki/data:/var/www/data

  dnsmasq:
    image: jpillora/dnsmasq
    container_name: Arcade_dns
    restart: always
    env_file: ./dnsmasq/env
    networks:
      arcade_vlan:
        ipv4_address: 172.16.64.4
    ports:
      - 53:53/udp
      - 8080:80/tcp
    volumes:
      - ./dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf:ro

networks:
  arcade_vlan:
    name: Arcade_net
    driver: macvlan
    driver_opts:
      parent: enp1s0.64
    ipam:
      config:
        - subnet: 172.16.64.0/28

volumes:
   roms:
     driver: local
     driver_opts:
       type: cifs
       device: \\172.16.4.4\Game\ROMs
       o: username=anonymous,ro,vers=3.0